### ISSUE TITLE
Create a check for DACs to valide fields

### ISSUE THREAD

**Issue by ste-bel** [Acumatica/Acuminator#138]
Could you include a verification when creating DAC or DACExtension to make sure each field has it's equivalent Property and vice-versa.  If one is missing then issue a warning.

public abstract class xxx : IBqlField { } // OK
public abstract class zzz : IBqlField { } // Issue warning

[PXDBInt]
public int? Xxx { get; set; } // OK

[PXDBInt]
public int? Yyy { get; set; } // Issue warning

**Comment by SENya1990** [comment]
@ste-bel, hi!
 We have such check in our plans. We will close the issue when is is implemented

**Comment by SENya1990** [comment]
New PX1065/PX1066 diagnostics checking this will be released in the next Acuminator version.
