### ISSUE TITLE
PX1088 Warning.

### ISSUE THREAD

**Issue by sampetrosov** [Acumatica/Acuminator#207]
I have code like below:

    public class IGSEQuickOrderProcess:PXGraph<IGSEQuickOrderProcess>
    {
        ...

        public static void ProcessOrders(List<IGSEQuickOrder> orders)
        {
            SOOrderEntry orderEntry = PXGraph.CreateInstance<SOOrderEntry>();
            for (int i=0;i<orders.Count;i++)
            {
                IGSEQuickOrder quickOrder = orders[i];
                orderEntry.Clear();
                SOOrder order = CreateOrder(quickOrder, orderEntry);
                if(QuickProcessOrder(order,orderEntry))
                {
                    PXProcessing<IGSEQuickOrder>.SetInfo(i, IGSEMessages.ProcessSuccess);
                }
		else
		{
                    PXProcessing<IGSEQuickOrder>.SetWarning(i, IGSEMessages.ProcessFailed);
                }
            }
        }

        public static SOOrder CreateOrder(IGSEQuickOrder quickOrder,SOOrderEntry sOOrderEntry)
        {
            //TODO Implement this method.
            SOOrder order = new SOOrder()
            {
                OrderType = "SO"
            };
            order = sOOrderEntry.Document.Insert(order);
            order.CustomerID = FindCustomerByCD(sOOrderEntry,quickOrder.CustomerID);
            return order;
        }

    }

I am getting the warning on the line `SOOrder order = CreateOrder(quickOrder, orderEntry);`
because of the `order = sOOrderEntry.Document.Insert(order);` line in the CreateOrder method.
But I don't see any problem here because I am using the DataView of the SOOrderEntry graph and not of the ProcessingGraph. Could you please check if this warning is correct or not?

**Comment by dropsonic** [comment]
Hi,
Seems like a false-positive warning. I'll create a bug for that. Thank you for reporting this issue!

**Comment by sampetrosov** [comment]
@dropsonic  Thank you for a quick response.

**Comment by metallmonster** [comment]
Hi @sampetrosov 
The bug was fixed in the latest version - 1.6. Please see Release Notes
https://github.com/Acumatica/Acuminator/blob/dev/docs/ReleaseNotes.md
