### ISSUE TITLE
The graph specified primary DAC type does not contain view of this type for F-BQL

### ISSUE THREAD

**Issue by YuriyZaletskyy** [Acumatica/Acuminator#239]
If graph uses SelectFrom instead of PXSelect then this error is shown:
The graph specified primary DAC type does not contain view of this type.
![githubIssue](https://user-images.githubusercontent.com/14317253/58184565-0881db00-7cba-11e9-848b-997558b927ce.png)

**Comment by SENya1990** [comment]
Hi, @YuriyZaletskyy . Could you please write the version of Acuminator and Visual Studio you use?

**Comment by YuriyZaletskyy** [comment]
@SENya1990 
Acumatica version 19.103.0030
Acuminator version 1.6.1

**Comment by SENya1990** [comment]
@YuriyZaletskyy and Visual Studio version? Do you use VS 2017 and the latest update?

**Comment by SENya1990** [comment]
Anyway I'll file a bug into our system and we will look into it.

**Comment by YuriyZaletskyy** [comment]
![visual studio version](https://user-images.githubusercontent.com/14317253/58233888-e6359f00-7d45-11e9-8c4a-c5a9d6fe0ce6.png)

**Comment by SENya1990** [comment]
@YuriyZaletskyy I have looked into this issue. You incorrectly use FBQL here. The `SelectFrom<Student2>` by itself is just a BQL command, it cannot be used as a view in graph. You need to write it like this:
```csharp
 public class StudentsFBQLMaint : PXGraph<StudentsFBQLMaint, Student2>
 {
	public SelectFrom<Student2>.View Students;
 }
```
