### ISSUE TITLE
PX1004 Warning

### ISSUE THREAD

**Issue by sampetrosov** [Acumatica/Acuminator#282]
I have the following Data View

`public PXSelect<BAccount, Where<BAccount.type, Equal<BAccountType.customerType>, Or<BAccount.type, Equal<BAccountType.combinedType>>>> CustomerCode;`

The warning is shown twice 

Severity	Code	Description	Project	File	Line	Suppression State
Message	PX1004	This order of view declarations will cause creation of two cache instances: Vendor and BAccount	IGRP	D:\Samvel\Acumatica\Projects\2019R1\IGRP\IGRP\IGRPInventoryItemMaintExt.cs	31	Active
Message	PX1004	This order of view declarations will cause creation of two cache instances: Customer and BAccount	IGRP	D:\Samvel\Acumatica\Projects\2019R1\IGRP\IGRP\IGRPInventoryItemMaintExt.cs	31	Active

If I change the Data View to the following only the warning for Customer and BAccount is shown

`public PXSelect<Customer, Where<Customer.type, Equal<BAccountType.customerType>, Or<Customer.type, Equal<BAccountType.combinedType>>>> CustomerCode;`

I don't have any other Data Views on Customer/Vendor/BAccount.
How can I change the code to remove this warning? 

This Data View is taken from the ARSalesPriceMaint and actually, there are 2 DataViews on BAccount/Customer in the ARSalesPriceMaint:

```
// PX.Objects.AR.ARSalesPriceMaint
// Token: 0x04008ACA RID: 35530
public PXSelect<Customer> Customer;

// PX.Objects.AR.ARSalesPriceMaint
// Token: 0x04008AC9 RID: 35529
public PXSelect<BAccount, Where<BAccount.type, Equal<BAccountType.customerType>, Or<BAccount.type, Equal<BAccountType.combinedType>>>> CustomerCode;

```

**Comment by SENya1990** [comment]
Hi @sampetrosov . What version of Acumatica and Acuminator you are using?

**Comment by sampetrosov** [comment]
@SENya1990 Acuminator 2.0.0 Acumatica 19.106.0020 Visual Studio 2019 Community 16.2.3

**Comment by SENya1990** [comment]
@sampetrosov PX1004/PX1006 have informational character - you don't have to change anything. However, they are actual only for Acumatica with version below 2018R2. Starting from the Acumatica 2018R2 version a new method `InitCacheMapping` is used to initialize caches with explicit ordering of caches. So that's a bug. We will fix it

**Comment by SENya1990** [comment]
Added fix with pull request https://github.com/Acumatica/Acuminator/pull/283/files
