### ISSUE TITLE
PXCustomizeBaseAttribute 

### ISSUE THREAD

**Issue by sampetrosov** [Acumatica/Acuminator#285]
Hi guys,

The below is not an issue, it is a suggestion based on the bad experience that I have had today.
Can you add checking for the PXCustomizeBaseAttribute to be applied only to CacheAttached event handler?

The system is throwing the following error in case if PXCustomizeBaseAttribute is used for example on the property in the DAC extension.
As you can see this exception doesn't describe the real reason.
![Property set method not found  - Google Chrome 2019-09-07 00 41 02](https://user-images.githubusercontent.com/15322805/64471640-c49bd000-d108-11e9-9caa-71b8f53c5968.png)

**Comment by SENya1990** [comment]
@sampetrosov thank you for your suggestion. We will discuss the possibility of such check

**Comment by Dmitrii-Naumov** [comment]
@sampetrosov I'vejust checked it on my instance and it seems it works fine for me. Here is the example that I've used:
`	public sealed class APTranExt : PXCacheExtension<APTran>
	{
		#region PONbr
		public abstract class pONbr : PX.Data.BQL.BqlString.Field<pONbr>
		{
		}
	//	[PXMergeAttributes(Method = MergeMethod.Append)]
		[PXCustomizeBaseAttribute(typeof(PXUIFieldAttribute),
			nameof(PXUIFieldAttribute.DisplayName), "PO NBR Base Currency Commission")]
		public string PONbr
		{
			get; set;
		}
		#endregion
	}`

Could you please specify the version of Acumatica ERP and share the code you've used?

**Comment by sampetrosov** [comment]
@Dmitrii-Naumov if I am not mistaken that was 19.193.0108. I have upgraded the instance to 19.200.0078 and haven't tried to repeat this issue.

**Comment by SENya1990** [comment]
@sampetrosov if possible please try to check if this behavior is still reproducible on your current version of Acumatica. If so, then it is probably some kind of bug in Acumatica platform because, as I understand, the PXCustomizeBaseAttribute should be possible to apply to a property of a DAC extension.

**Comment by sampetrosov** [comment]
@SENya1990 @Dmitrii-Naumov I checked on the 19.200.0078 and it is working for me too. Maybe this was caused by pre-release version. I am not sure, but I will inform you if I get this issue again.
