### ISSUE TITLE
Possible null dereference. Consider inspecting 'newNode'. BqlRewriterBase.cs 64

### ISSUE THREAD

**Issue by SashaSenichkin** [Acumatica/Acuminator#290]
Acuminator.Vsix.Formatte.BqlRewriterBase.RewriteGenericNode
OnNewLineAndIndented can return null

**Comment by SENya1990** [comment]
@SashaSenichkin I'll check it. Thanks a lot for your help.

**Comment by SENya1990** [comment]
Created pull request with a check for null:
https://github.com/Acumatica/Acuminator/pull/292/files
