### ISSUE TITLE
Possible null dereference of method return value. Consider inspecting: GetUnderlyingTypeFromNullable(...). LegacyBqlFieldAnalyzer.cs 64

### ISSUE THREAD

**Issue by SashaSenichkin** [Acumatica/Acuminator#291]
Acuminator.Analyzers.StaticAnalysis.LegacyBqlField.LegacyBqlFieldAnalyzer.GetPropertyTypeName
namedType.GetUnderlyingTypeFromNullable(pxContext) can return null

**Comment by SENya1990** [comment]
@SashaSenichkin I'll investigate the problem and close the issue when I'll fix it. Many thanks for your help

**Comment by SENya1990** [comment]
Created pull request with a check for null:
https://github.com/Acumatica/Acuminator/pull/292/files
