### ISSUE TITLE
PX1094 with PXMappedCacheExtension

### ISSUE THREAD

**Issue by bhennelly** [Acumatica/Acuminator#323]
Is it intended that we add PXHidden or PXCacheName to a PXMappedCacheExtension? Understanding it inherits from PXCacheExtension does it apply in this case as a mapped cache extension is used a little differently?

This is more of a question than an issue unless PX1094 should be ignored for PXMappedCacheExtension

**Comment by SENya1990** [comment]
@bhennelly hi. Probably we shouldn't check PXMappedCacheExtension with this diagnostic. I will create a change request. I'll close this request when we implement the change

**Comment by SENya1990** [comment]
the issue is fixed in upcoming version 2.1.3 with pull request
https://github.com/Acumatica/Acuminator/pull/334
