### ISSUE TITLE
Acuminator doesn't take into account inherited IsActive property

### ISSUE THREAD

**Issue by YuriyZaletskyy** [Acumatica/Acuminator#386]
In my code I have written code like this:

public class ActiveGraphExtension<T> : PXGraphExtension<T> where T : PXGraph
{
        public static bool IsActive() => true;
}

Then for my graph extension I write code like this:

 public class KNRWAPInvoiceEntryExt : ActiveGraphExtension<APInvoiceEntry>
 {
        public PXFilter<KNRWGSTTax> GSTDetails;
}

but Acuminator is blind toward that inheritance, and gives me this error message:

![image](https://user-images.githubusercontent.com/14317253/98915522-b1d21780-24d2-11eb-8b35-2c0521e10acd.png)

**Comment by dropsonic** [comment]
Hi Yuriy,
That's correct. You should define `IsActive` in the derived class - it is a static method that is not inherited via .NET nor collected by our framework.

However, I'd like to note that there is no point in declaring an empty `IsActive` method that always returns `true`.
It is recommended to suppress the diagnostic with a suppression comment providing a justification why this particular extension should always be on.
