### ISSUE TITLE
Acuminator doesn't see inhertitance for Graph Extension

### ISSUE THREAD

**Issue by YuriyZaletskyy** [Acumatica/Acuminator#387]
In my code I have written code like this:

public class ActiveGraphExtension : PXGraphExtension where T : PXGraph
{
public static bool IsActive() 
{
     if(some validation logic)
     {
          return true;
     }
     return false;
}
}

Then for my graph extension I write code like this:

public class KNRWAPInvoiceEntryExt : ActiveGraphExtension
{
 
}

but Acuminator is blind toward that inheritance
In order to avoid code duplication, I'd like to have option to re-use inheritance instead of copy/pasting the same code in IsActive methods in each graph extension.

**Comment by SENya1990** [comment]
Hi @YuriyZaletskyy this is a change request to Acumatica itself, not Acuminator. We already have such item logged into our platform team backlog. Currently the only correct behavior is to declare `IsActive` in all derived graph extensions for concrete graphs. Therefore Acuminator will check each derived graph extension until the behavior is changed.

**Comment by SENya1990** [comment]
It is not an issue in Acuminator. It is a behavior of Acumatica Framework which does not check for IsActive method declaration in the base classes of extension. Acuminator does not see IsActive in the base class because run-rime won't see it.

**Comment by dropsonic** [comment]
Duplicate of #386
