### ISSUE TITLE
Acuminator Not Compatible With VS Previews

### ISSUE THREAD

**Issue by ShadowFiendZX** [Acumatica/Acuminator#402]
A VS preview was released today which is supposed to fix a bug in Microsoft's code that causes it to crash under various circumstances. I found that Acuminator doesn't work with previews.
In src\Acuminator\Acuminator.Vsix\Utils\Version\VSVersionProvider.cs line 39, Acuminator creates a Version instance based on an object gotten from a service. 
The string returned is "16.11.0 Preview 3.0", which Version evidently doesn't like, causing a string format error.
I added this above the line in question : 
`if (versionObj.ToString() == "16.11.0 Preview 3.0")
{
    versionObj = "16.11.3";
}`

This fixes the string format error, although I'm not sure if Preview 3 would technically be 16.11.3.

**Comment by SENya1990** [comment]
Hi @ShadowFiendZX. 

Many thanks for your input!
If you don't mind could you please create PR to the `dev` branch of Acuminator and add me and @dropsonic  as reviewers?

Please write here If you can't create PR due to insufficient rights. Please also write if you won't be able to this due the some other things, so I'll put the fix myself when I've got the time to do it.

**Comment by ShadowFiendZX** [comment]
Sorry it took so long, it took a while to write the code since my VS is set to automatically fix spaces vs tabs (in favor of tabs), remove unused usings, and sort usings and I didn't want to disturb the code too much. It also took a while to make everything fit within the indentation limit.

I am receiving a 403 when trying to push, saying it's unable to access, but I think it may be because my VS is logged into my work MS account but my github uses my personal email.

**Comment by SENya1990** [comment]
It shouldn't really matter I think. I'll try to clarify this issue.

**Comment by SENya1990** [comment]
@ShadowFiendZX please check your email, an invite with access rights was sent to you

**Comment by SENya1990** [comment]
Fixed with PR:
https://github.com/Acumatica/Acuminator/pull/403

@ShadowFiendZX thanks for your help!
