### ISSUE TITLE
Descriptors are internal static class.

### ISSUE THREAD

**Issue by sampetrosov** [Acumatica/Acuminator#41]
Your **Acuminator.Tests** project is not building as you are trying to use `Descriptors` class like below:

```
var diagnostic = new DiagnosticResult
{
	Id = Descriptors.PX1001_PXGraphCreateInstance.Id,
	Message = Descriptors.PX1001_PXGraphCreateInstance.Title.ToString(),
	Severity = DiagnosticSeverity.Error,
	Locations = new[] {
		                   new DiagnosticResultLocation("Test0.cs", line, column)
                            }
};
```
but that class is in the `Acuminator.Analyzers` namespace and it is `internal`.

**Comment by SENya1990** [comment]
@sampetrosov, yes, that's why in Analyzers AssemblyInfo.cs there is InternalsVisibleTo attribute referring to Tests project.

**Comment by dropsonic** [comment]
Hi,

**Acuminator.Diagnostics** has `InternalsVisibleTo` attribute inside `AssemblyInfo.cs` which makes all `internal` types visible to **Acuminator.Tests** project. You should replace the default assembly key there with your own one.
