### ISSUE TITLE
How to use Acuminator?

### ISSUE THREAD

**Issue by sampetrosov** [Acumatica/Acuminator#42]
Can you please add an instruction on how to use "Acuminator" in the Visual Studio to do the Static Analyze?

**Comment by dropsonic** [comment]
What kind of instruction would you like to see?
Acuminator works as any default static code analyzer built in Visual Studio.
After Acuminator is installed, it shows you warnings/errors in your code as Visual Studio does.

**Comment by SENya1990** [comment]
@sampetrosov, the static analysis is performed on open files automatically. If you want to analyze the whole solution you should go to VS options: Tools -> Options -> Text Editor -> C# -> Advanced -> Enable full solution analysis

**Comment by SENya1990** [comment]
@sampetrosov, then you can see errors in "Error List" window (View -> Error List).
@dropsonic, correct me if I'm wrong, but currently this is the only way to analyze whole solution in VS.

**Comment by sampetrosov** [comment]
@dropsonic @SENya1990 I mean how should I install the resulting `Acuminator.dll` in the Visual Studio so that it starts working? I know how to use the analyzer, but I couldn't install it.

**Comment by SENya1990** [comment]
@sampetrosov, currently we use VSIX to install Acuminator

**Comment by SENya1990** [comment]
@sampetrosov, you should build Acuminator in Release mode then find Acuminator.vsix in ..\Acuminator.Vsix\bin\Release and the VS installer will install it for you.

**Comment by dropsonic** [comment]
@sampetrosov open your Visual Studio, go to Tools menu, Extensions & Updates, and type "Acumatica" or "Acuminator" in the search field. Then install it as any other Visual Studio extension.

**Comment by SENya1990** [comment]
@sampetrosov, if you want to just install released version then you should use @dropsonic suggestion. If you want to build from sources then use mine

**Comment by sampetrosov** [comment]
@SENya1990 oops, I forgot to look for VSIX and was trying to add the analyzer as `Dll` to the project. I just run the "Acuminator.vsix" file and it installed the analyzer. Thank you very much.
