### ISSUE TITLE
Warning PX1012 is always shown if Graph is inherited from PXGraph<TGraph>.

### ISSUE THREAD

**Issue by sampetrosov** [Acumatica/Acuminator#43]
The analyzer is always showing PX1012 Warning for all `PXAction`s in the graphs inherited from `PXGraph<TGraph>`. 
![screenshot](https://user-images.githubusercontent.com/15322805/42511757-d11cd27c-8463-11e8-8aa1-38b8ca116439.png)

**Comment by SENya1990** [comment]
@sampetrosov, yes, this is known issue because currently the PX1012 diagnostic is still experimental (it is not officially published yet) and determines the primary view as the first view of the graph.

**Comment by sampetrosov** [comment]
@SENya1990 should I close this issue or leave it open?

**Comment by SENya1990** [comment]
@sampetrosov, it is impossible to precisely determine primary view without aspx analysis but we work on фт heuristic algorithm to deduce primary view of the graph.

**Comment by SENya1990** [comment]
@sampetrosov, you can leave the issue open. We'll close it when we update the diagnostic

**Comment by sampetrosov** [comment]
@SENya1990 I have noticed today that if `PXSelect<PRIMARY_DAC>` in the `Graph` is going before any other selects and actions this warning is not being shown.

**Comment by SENya1990** [comment]
@sampetrosov , yes because that's exactly how the first version of the diagnostic was implemented - to use the DAC from first view as primary DAC if the primary DAC wasn't specified in the graph class declaration

**Comment by SENya1990** [comment]
@sampetrosov, this proved to be wrong for many cases. You're using not published, "experimental" Acuminator with exactly this version of the diagnostic. However, you can supress this warning  in your code (as Visual Studio suggests) or in the ruleset file (open Solution explorer, see your project's References, find Analyzers, right click and choose "Open active rule" set in context menu)

**Comment by SENya1990** [comment]
The new implementation of diagnostic was merged into master so this issue should be closed
