### ISSUE TITLE
Question about rule PX1030 "The PXDefault attribute of the field is used incorrectly."

### ISSUE THREAD

**Issue by eberlekhaufe** [Acumatica/Acuminator#531]
In order to make a field in a DAC extension mandatory, the acumatica docs say to use the PXDefault attribute (with PersistenceCheck.Null or PersistenceCheck.NullOrBlank). See https://help.acumatica.com/(W(45))/Help?ScreenId=ShowWiki&pageid=97f5b92f-906a-4edd-ae38-f5605e83d845. section "_To Make a Custom Field Mandatory on the DAC Level_". 

That however violates against acuminator's rule [PX1030](https://github.com/Acumatica/Acuminator/blob/dev/docs/diagnostics/PX1030.md).

acuminator's suggestion to use PersistenceCheck.Nothing does not work here, because that would not make the field mandatory anymore.

I can of course disable the rule in the particular case.
But as the rule is of type "Warning (ISV Level 1: Significant) or Error" I have wondered what the recommended way is in order to make a field mandatory in a DAC extension?

**Comment by SENya1990** [comment]
Hi @eberlekhaufe,

Thanks for reaching out! 
If I remember correctly, the main reason behind the recommendation to avoid adding mandatory fields to DAC in a DAC extension is to correctly worked with the existing data in the DB table. 

DAC extensions are frequently used to extend existing DACs that extensions' authors do not control. Before the PX1030 diagnostic creation, DAC extension developers quite often declared new mandatory DAC fields without understanding that they are corrupting  the existing DAC records in the DB. The reason of such corruption is simple. The existing DAC records didn't have the new field set. So, on any attempt to modify and save the existing document the `PXDefault` attribute raised and error. 
This error prevented users from saving their changes to the DB until they set the new mandatory field. Very frequently, the existing documents were already released and didn't allow users to set the new required field. This resulted in support requests that were usually resolved with the manual DB manipulations. The PX1030 check was created to check for such scenarios.

However, notice that the severity of PX1030 diagnostic is "Warning", not "Error". I would say that adding mandatory DAC fields in DAC extensions requires an extra level of caution. You should not do this, if you don't really need a mandatory field. 
But, if you absolutely need a mandatory DAC field, I believe you can suppress the diagnostic with a suppression comment. 
**You will also need to perform an extra work to make sure that the data created before the introduction of your DAC extension will work correctly.** Usually, this involves writing SQL scripts which will update the existing data with uninitialized new column. They can look similar to this:
```sql
  UPDATE MyDac
  SET NewField = 'Default Value' 
  WHERE NewField IS NULL
```
Keep in mind that such scripts may be executed more than once and they must not corrupt records with already initialized data.
For a more complex logic you may need to write a customization plugin, or more complex business logic.

As for the article you are referring to (https://help.acumatica.com/Help?ScreenId=ShowWiki&pageid=97f5b92f-906a-4edd-ae38-f5605e83d845) - the article itself is not a recommendation or a best practice. It does not advice you to make your DAC extension fields mandatory. It provides a guide on how to do this if you need it. So, I would say that there is nothing wrong with it. Still, I will discuss with our Documentation team, if the PX1030 diagnostic should be mentioned there.

**Comment by eberlekhaufe** [comment]
Thanks for your reply. No objection against the need to make the column nullable in the DB. 

But from a UX perspective there must be a way to make the field mandatory for users in the UI if the field comes from a customization. A user does not care about the technical layers of the code, he just sees a screen with fields and relies on the good UX that fields which are mandatory are really enforced by the software.

From what I have seen, just using PXUIField(Required=true) is not sufficient. It shows the red asterisk, but you can leave the field empty and saving still works. Only when additionally you set PXPersistenceCheck.Null or NullOrBlank, the user gets the desired error if he saves and the field is empty.

Still wondering whether the severity of the rule should not even be warning, as I cannot resolve it other than suppressing the rule. What do you think?

**Comment by SENya1990** [comment]
@eberlekhaufe there is nothing wrong with adding a mandatory DAC field with `PXDBDefault`, if that is what you absolutely need, and you understand and make all work required to correctly handle existing DAC records - write upgrade scripts, etc.  

The goal of PX1030 rule is to alert developers who are adding a mandatory DAC field via extension about the potential data consistency pitfall. There is nothing wrong with suppressing the warning from this rule. With suppression you just state that you know what you are doing and understand all required actions. 

Suppression is a part of work with the static code analysis. There is no problem to suppress a warning or error if you know better. There are other Acuminator rules that frequently rely on suppression like PX1016 that checks for the presence of the `IsActive` method in extension. If your extension should be always active, then the rule should be suppressed.

**Comment by SENya1990** [comment]
PS: I have discussed this question with Acumatica Doc team and asked them to mention the potential problem with the addition of mandatory fields in a DAC extension. With this, I believe the question should be closed.
