### ISSUE TITLE
Use of PXPrimaryGraph results in message "PXGraph instances cannot be used inside DAC properties"

### ISSUE THREAD

**Issue by bhennelly** [Acumatica/Acuminator#73]
Found the message "PXGraph instances cannot be used inside DAC properties" on the use of PXPrimaryGraph(tyepof(MyGraphName)) as shown in the attached screen shot (Acuminator 1.3.0)

![image](https://user-images.githubusercontent.com/25390714/44601444-7ee4c180-a7aa-11e8-9349-21cdf8477eb2.png)

**Comment by SENya1990** [comment]
@bhennelly, thanks. We will upgrade this diagnostic to fix the problem

**Comment by SENya1990** [comment]
The issue was resolved and merged into master
